routes/admin.php
<?php


use Illuminate\Support\Facades\Route;


Route::get('/', 'LoginController@index')->name('login');
Route::get('login', 'LoginController@index')->name('login');

Route::post('login', 'LoginController@loginCheck')->name('loginCheck');

Route::group(['middleware' => ['auth:admin', 'adminLanguage']], function () {

    Route::get('dashboard', 'HomeController@index')->name('dashboard');


    Route::resource('user', 'UserController');
    Route::get('userDetails/{id}', 'UserController@userDetails')->name('userDetails');

    Route::get('user/status/{id}/{status}', 'UserController@changeStatus')->name('user.status.change');


    Route::get('profile', 'AdminController@profile')->name('profile');
    Route::post('updateProfile', 'AdminController@updateProfile')->name('updateProfile');


    Route::post('editProfile', 'AdminController@editProfile')->name('editProfile');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('password', 'AdminController@password')->name('password');
    Route::post('updatePassword', 'AdminController@updatePassword')->name('updatePassword');

    Route::resource('village', 'VillageController');
    Route::resource('relation', 'RelationController');

    Route::resource('notification', 'NotificationController');
    Route::resource('diksarthi', 'DiksarthiController');
    Route::get('setting', 'SettingController@index')->name('setting');
    Route::post('updateSetting', 'SettingController@updateSetting');
    Route::get('import', 'UserController@import');
    Route::post('fileImport', 'UserController@fileImport');
    Route::get('familyMember/{id}', 'UserController@familyMember')->name('familyMember');
    Route::get('familyMemberList', 'UserController@familyMemberList')->name('familyMemberList');
    Route::get('familyUser/{id}', 'UserController@familyUser')->name('familyUser');
    Route::resource('circular', 'CircularController');
    Route::resource('feedback', 'FeedbackController');
    Route::resource('yojna', 'YojnaController');
    Route::resource('gallery', 'GalleryController');
    Route::post('imageUpload', 'GalleryController@imageUpload')->name('imageUpload');
    Route::post('addVideoLink', 'GalleryController@addVideoLink')->name('addVideoLink');
    Route::delete('imageDelete/{id}', 'GalleryController@imageDelete')->name('imageDelete');
    Route::post('getGalleryImage', 'GalleryController@getGalleryImage')->name('getGalleryImage');
    Route::get('deleteGalleryImage/{id}', 'GalleryController@deleteGalleryImage')->name('deleteGalleryImage');

    Route::resource('tapasviSamman', 'TapasviSammanController');
    Route::resource('parshwanath', 'ParshwanathController');
    Route::resource('villageDerasar', 'VillageDerasarController');
    Route::resource('ourAncestor', 'OurAncestorController');
    Route::resource('ourGyanti', 'OurGyantiController');
    Route::resource('banner', 'BannerController');
    Route::resource('template', 'TemplateController');
    Route::resource('president', 'PresidentController');
    Route::resource('ourCommitte', 'OurCommitteController');
    Route::resource('karyakar', 'KaryakarController');
    Route::resource('page', 'PageController');

    Route::get('sendEmail', 'CommunicationController@sendEmail')->name('sendEmail');
    Route::get('sendSms', 'CommunicationController@sendSms')->name('sendSms');
    Route::get('sendNotification', 'CommunicationController@sendNotification')->name('sendNotification');
    Route::post('sendEmailProcess', 'CommunicationController@sendEmailProcess')->name('sendEmailProcess');
    Route::post('sendNotificationProcess', 'CommunicationController@sendNotificationProcess')->name('sendNotificationProcess');
    Route::get('ownershipTransfer/{id}', 'UserController@ownershipTransfer')->name('ownershipTransfer');
    Route::post('ownershipTransfer', 'UserController@ownershipTransferSubmit')->name('ownershipTransferSubmit');
    Route::get('todayBirthday', 'BirthdayController@todayBirthday')->name('todayBirthday');
    Route::get('todayBirthdaySend', 'BirthdayController@todayBirthdaySend')->name('todayBirthdaySend');
    Route::get('todayAnniversary', 'BirthdayController@todayAnniversary')->name('todayAnniversary');
    Route::get('todayAnniversarySend', 'BirthdayController@todayAnniversarySend')->name('todayAnniversarySend');
    Route::get('exportUser', 'UserController@export')->name('exportUser');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function(){
    return redirect('admin/login');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/privacy-policy', 'HomeController@page')->name('privacy-policy');
Route::get('reset-password/{token}', 'ResetPasswordController@resetPasswordForm')->name('reset-password');
Route::post('resetPasswordSubmit', 'ResetPasswordController@resetPasswordSubmit')->name('resetPasswordSubmit');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function relation()
    {
        return $this->belongsTo(Relation::class);
    }

    public function familyMember()
    {
        return $this->hasMany(User::class, 'main_member_id');
    }

    public function village()
    {
        return $this->belongsTo(Village::class);
    }
}

app/Http/Controllers/Api/V1/UserController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Helpers\ImageDeleteHelper;
use App\Helpers\ImageUploadHelper;
use App\Http\Controllers\Controller;
use App\Http\Requests\API\V1\UserChangePasswordRequest;
use App\Http\Requests\API\V1\UserProfileChangeRequest;
use App\Http\Requests\API\V1\UserProfileUpdateRequest;
use App\Http\Resources\UserResource;
use App\Mail\ResetPasswordEmail;
use App\Models\User;
use App\Models\UserDevice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function index( Request $request ): \Illuminate\Http\JsonResponse
    {
        $user = $request->user();

        return response()->json([
            'data' => new UserResource($user),
        ]);
    }

    public function memberList( Request $request )
    {
        $users = User::with('village');
        if ($request->input('family') != null) {
            //$user = User::where('id', $request->input('family'))->first();
//            if ($user && $user->member_type == 2) {
//                $users = $users->where('main_member_id', $user->main_member_id);
//            } else {
            $users = $users->where('main_member_id', $request->input('family'));
//            }

        }
        if ($request->input('member_type') != null) {
            $users = $users->where('member_type', $request['member_type']);
        }
        if ($request->input('search') != null) {
            $users = $users->where(function ( $query ) use ( $request ) {
                $query->where('name', 'LIKE', '%' . $request['search'] . '%')
                    ->orwhere('mobile_no', 'LIKE', '%' . $request['search'] . '%')
                    ->orwhere('email', 'LIKE', '%' . $request['search'] . '%');
            });
        }
        if ($request->input('village_id') != null) {
            $users = $users->where('village_id', $request->input('village_id'));
        }
        $users = $users->paginate(10);

        return response()->json([
            'data'        => UserResource::collection($users),
            'total_pages' => ceil($users->total() / 10)
        ]);
    }

    public function updateProfile( UserProfileUpdateRequest $request ): \Illuminate\Http\JsonResponse
    {
        $validated = $request->validated();

        try {
            $user = User::findorFail($request->user()->id);
            $user->name = $validated['name'];
            $user->mobile_no = $validated['mobile_no'];
            $user->email = $validated['email'];
            $user->village_id = $request['village_id'];
            $user->petron = $request['petron'];
            $user->piyar_paksh = $request['piyar_paksh'];
            $user->anniversary_date = $request['anniversary_date'];
            $user->date_of_birth = $request['date_of_birth'];
            $user->education = $request['education'];
            $user->marital_status = $request['marital_status'];
            $user->blood_group = $request['blood_group'];
            $user->residency_no = $request['residency_no'];
            $user->address_1 = $request['address_1'];
            $user->address_2 = $request['address_2'];
            $user->address_3 = $request['address_3'];
            $user->city = $request['city'];
            $user->pincode = $request['pincode'];
            $user->special = $request['special'];
            $user->office_no = $request['office_no'];
            $user->business = $request['business'];

            if ($request->hasFile('image')) {
                $image = ImageUploadHelper::ImageUpload($request['image']);
                $user->image = $image;
            }

            $user->save();
            return response()->json([
                'success' => true,
                'message' => trans('messages.api.user.profile_updated'),
            ]);
        } catch (\Exception $error) {
            return response()->json([
                'success' => false,
                'message' => "API Error.",
                'error'   => $error->getMessage() . '.line-' . $error->getLine(),
            ]);
        }
    }

    public function changePassword( UserChangePasswordRequest $request ): \Illuminate\Http\JsonResponse
    {
        $validated = $request->validated();

        try {
            $user = User::findorFail($request->user()->id);
            if (Hash::check($validated['old_password'], $user->passwod)) {
                $user->passwod = $validated['new_password'];
                $user->save();
                return response()->json([
                    'message' => trans('messages.api.user.password_updated'),
                ]);
            } else {
                return response()->json([
                    'message' => trans('messages.api.user.old_password_is_wrong'),
                ], 422);
            }
        } catch (\Exception $error) {
            return response()->json([
                'message' => trans('messages.api.error'),
                'error'   => $error->getMessage(),
            ], 500);
        }
    }

    public function forgotPassword( Request $request ): \Illuminate\Http\JsonResponse
    {
        $rules = [
            'email' => 'required|email',
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->errors()->first(),
            ], 403);
        }
        $user = User::where(['email' => $request->input('email')])->first();
        if ($user) {
            $token = Password::getRepository()->create($user);
            $array = [
                'name'                   => $user->name,
                'actionUrl'              => route('reset-password', [$token]),
                'mail_title'             => trans('messages.title_password_reset'),
                'reset_password_subject' => trans('messages.reset_password_subject'),
                'main_title_text'        => trans('messages.title_password_reset'),
            ];
            Mail::to($request->input('email'))->send(new ResetPasswordEmail($array));
            return response()->json([
                'success' => true,
                'message' => trans('messages.please_check_your_mail'),
            ], 200);
        } else {
            return response()->json([
                'success' => false,
                'message' => trans('messages.email_not_found'),
            ], 200);
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.vertical', ['title' =>"Add Member"])

@section('content')
    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">

                    <h4 class="page-title">Add Member</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        <form role="form" data-toggle="validator" id="addEditForm" autocomplete="off"
                              method="post" class="needs-validation" novalidate enctype="multipart/form-data">
                            <input type="hidden" id="form-method" value="edit">
                            <input type="hidden" name="edit_value" value="0">
                            @csrf
                            <div class="row">
                                <div class="col-12 form-group mb-3">
                                    <label>Member Type</label>
                                    <select name="member_type" class="form-control select2" id="member_type" required>
                                        <option value="">Select Type</option>
                                        <option value="1">Registered Member</option>
                                        <option value="2">Family Member</option>
                                    </select>
                                </div>
                                <div class="col-12 form-group mb-3 register_member" style="display: none">
                                    <label>Select Main Member</label>
                                    <select name="main_member_id" class="form-control select2" id="main_member_id"
                                            >
                                        <option value="">Select Member</option>
                                        @foreach($register_members as $register_member)
                                            <option value="{{$register_member->id}}" data-family-no="{{$register_member->family_no}}">{{$register_member->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="col-6 form-group mb-3">
                                    <label>Full Name</label>
                                    <input type="text" class="form-control" name="name"
                                           placeholder="Name" required>
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Village</label>
                                    <select name="village_id" id="village_id" class="form-control select2">
                                        <option value="">Select Village</option>
                                        @foreach($villages as $village)
                                            <option value="{{$village->id}}">{{$village->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                               
                                <div class="col-6 form-group mb-3">
                                    <label>Family No</label>
                                    <input type="text" class="form-control" id="family_no" name="family_no"
                                           placeholder="Family No" required>
                                </div>

                                <div class="col-6 form-group mb-3">
                                    <label>Person No</label>
                                    <input type="text" class="form-control" name="per_no"
                                           placeholder="Person No" required>
                                </div>

                                <div class="col-6 form-group mb-3">
                                    <label>Relation</label>
                                    <select name="relation_id" id="relation_id" class="form-control select2">
                                        <option value="">Select Relation</option>
                                        @foreach($relations as $relation)
                                            <option value="{{$relation->id}}">{{$relation->name}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="col-6 form-group mb-3">
                                    <label>Petron or Life</label>
                                    <select name="petron" id="petron" class="form-control select2">
                                        <option value="">Select Type</option>
                                        <option value="P">Petron</option>
                                        <option value="L">Life</option>
                                    </select>
                                </div>

                                <div class="col-6 form-group mb-3">
                                    <label>Piyar Paksh</label>
                                    <input type="text" class="form-control" name="piyar_paksh"
                                           placeholder="Piyar Paksh">
                                </div>

                                <div class="col-6 form-group mb-3">
                                    <label>Anniversary Date</label>
                                    <input type="text" id="anniversary_date" class="form-control"
                                           name="anniversary_date"
                                           placeholder="Anniversary Date">
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Birth Date</label>
                                    <input type="text" id="date_of_birth" class="form-control"
                                           name="date_of_birth"
                                           placeholder="Birth Date">
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Education</label>
                                    <input type="text" class="form-control"
                                           name="education"
                                           placeholder="Education">
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Marital Status</label>
                                    <select name="marital_status" id="marital_status" class="form-control select2">
                                        <option value="">Select Type</option>
                                        <option value="Married">Married</option>
                                        <option value="Unmarried">Unmarried</option>
                                        <option value="Engaged">Engaged</option>
                                    </select>
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Mobile No</label>
                                    <input type="text" class="form-control integer" name="mobile_no"
                                           placeholder="Mobile No"
                                    >
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Email</label>
                                    <input type="email" class="form-control" name="email"
                                           placeholder="Email"
                                    >
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Blood Group</label>
                                    <input type="text" class="form-control"
                                           name="blood_group"
                                           placeholder="Blood Group">
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Residency No</label>
                                    <input type="text" class="form-control" name="residency_no"
                                           placeholder="Residency No"
                                    >
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Office No</label>
                                    <input type="text" class="form-control" name="office_no"
                                           placeholder="Office No"
                                    >
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Business</label>
                                    <textarea class="form-control" name="business"
                                              placeholder="Business"
                                    ></textarea>
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Address 1</label>
                                    <textarea class="form-control" name="address_1"
                                              placeholder="Address 1"
                                    ></textarea>
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Address 2</label>
                                    <textarea class="form-control" name="address_2"
                                              placeholder="Address 2"
                                    ></textarea>
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Address 3</label>
                                    <textarea class="form-control" name="address_3"
                                              placeholder="Address 3"
                                    ></textarea>
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>City</label>
                                    <input type="text" class="form-control" name="city"
                                           placeholder="City"
                                    >
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Pincode</label>
                                    <input type="text" class="form-control" name="pincode"
                                           placeholder="pincode"
                                    >
                                </div>
                                <div class="col-6 form-group mb-3">
                                    <label>Special</label>
                                    <textarea class="form-control" name="special"
                                              placeholder="Special"
                                    ></textarea>
                                </div>
                                <div class="col-12 form-group mb-3">
                                    <label>Image</label>
                                    <input type="file" name="image" class="dropify"/>
                                </div>
                                <div class="col-12 form-group mb-3">
                                    <label>Password</label>
                                    <input type="password" class="form-control" name="password"
                                           placeholder="Password">
                                </div>
                            </div>

                            <button class="btn btn-primary" id="update-btn"
                                    type="submit">{{trans('messages.submit')}}
                            </button>

                            <a class="btn btn-dark"
                               href="{{route('admin.user.index')}}">{{trans('messages.cancel')}}</a>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('admin/assets/js/custom/user.js') }}?v={{ time() }}"></script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.vertical', ['title' => 'Members'])

@section('content')

    <style>
        td.details-control {
            background: url('https://datatables.net/examples/resources/details_open.png') no-repeat center center;
            cursor: pointer;
        }

        tr.shown td.details-control {
            background: url('https://datatables.net/examples/resources/details_close.png') no-repeat center center;
        }

    </style>
    <!-- Start Content-->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <a href="{{route('admin.user.create')}}" class="btn btn-primary">Add Member</a>
                    </div>
                    <h4 class="page-title">Members</h4>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-lg-3">
                            <select name="village_id" id="village_id" class="form-control select2">
                                <option value="">Select Village</option>
                                @foreach($villages as $village)
                                    <option value="{{$village->id}}">{{$village->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-lg-3">
                            <select name="member_type" id="member_type" class="form-control select2">
                                <option value="">Select Type</option>
                                <option value="1">Registered Member</option>
                                <option value="2">Family Member</option>
                            </select>
                        </div>
                        <div class="col-lg-3">
                            <button class="btn btn-primary" id="filter">Filter</button>
                            <button class="btn btn-success" id="export">Export</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Add rows table -->
        <section id="add-row">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table add-rows" id="addrows">
                                        <thead class="thead-dark">
                                        <tr>
                                            <th></th>
                                            <th>{{trans('messages.id')}}</th>
                                            <th>Member Type</th>
                                            <th>Village</th>
                                            <th>Family ID</th>
                                            <th>{{trans('messages.name')}}</th>
                                            <th>{{trans('messages.mobile_no')}}</th>
                                            <th>Birth Date</th>
                                            <th>Relation</th>
                                            <th>{{trans('messages.status')}}</th>
                                            <th>{{trans('messages.action')}}</th>
                                        </tr>
                                        </thead>
                                        <tfoot class="thead-dark">
                                        <tr>
                                            <th></th>
                                            <th>{{trans('messages.id')}}</th>
                                            <th>Member Type</th>
                                            <th>Village</th>
                                            <th>Family ID</th>
                                            <th>{{trans('messages.name')}}</th>
                                            <th>{{trans('messages.mobile_no')}}</th>
                                            <th>Birth Date</th>
                                            <th>Relation</th>
                                            <th>{{trans('messages.status')}}</th>
                                            <th>{{trans('messages.action')}}</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@section('script')
    <script>
        const destroy_user = '{{trans('messages.admin.user.destroy_user')}}'
        const delete_message = '{{trans('messages.delete_message')}}'
        const status_message = '{{trans('messages.status_message')}}'
        const active_user = '{{trans('messages.admin.user.active_user')}}'
        const inactive_user = '{{trans('messages.admin.user.inactive_user')}}'
    </script>
    <script src="{{ asset('admin/assets/js/custom/user.js') }}?v={{ time() }}"></script>

@endsection